
set(VMMLIB_PACKAGE_VERSION 1.7.0)
set(VMMLIB_REPO_URL https://github.com/Eyescale/vmmlib.git)
set(VMMLIB_REPO_TAG 1.7)
set(VMMLIB_DEPENDS OPTIONAL OpenMP LAPACK CBLAS)
set(VMMLIB_FORCE_BUILD ${CI_BUILD})
